version: '3'
services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - 5000:5000
      - 5001:5001
    networks:
      - just-trade-it-network
  
  notification-service:
    build: ./notification-service
    container_name: notification-service
    networks:
      - just-trade-it-network
  
  message-broker:
    image: rabbitmq
    hostname: message-broker
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_VHOST: /
    container_name: message-broker
    networks:
      - just-trade-it-network

networks:
  just-trade-it-network:
    driver: bridge
